spring.application.name=DigitalBankSystem

spring.datasource.url=jdbc:mysql://mysql:3306/digital_bank
spring.datasource.username=default_user
spring.datasource.password=default_password
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
